# Generated by Django 4.1.7 on 2023-03-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stackoverflow',
            name='age_first_code',
        ),
        migrations.AddField(
            model_name='stackoverflow',
            name='max_age_first_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='stackoverflow',
            name='min_age_first_code',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
