# Generated by Django 4.1.7 on 2023-03-04 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0002_remove_stackoverflow_age_first_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stackoverflow',
            name='gdp',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses', to='readers.gdp'),
        ),
    ]
