# Generated by Django 4.1.7 on 2023-03-04 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0003_stackoverflow_gdp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stackoverflow',
            name='languages_raw',
        ),
        migrations.CreateModel(
            name='ProgrammingLanguageResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('survey_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='readers.stackoverflow')),
            ],
        ),
    ]
