# Generated by Django 4.1.7 on 2023-03-05 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0004_remove_stackoverflow_languages_raw_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stackoverflow',
            name='gdp',
        ),
    ]
