# Generated by Django 4.1.7 on 2023-03-05 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0005_remove_stackoverflow_gdp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GDP',
            new_name='GrossDomesticProduct',
        ),
        migrations.RenameModel(
            old_name='StackOverflow',
            new_name='StackOverflowResponse',
        ),
    ]
